version: '3.8'

services:
  vite-app:
    build: .
    ports:
      - "5173:5173"
    command: ["sh", "-c", "docker ps -q --filter publish=5173 | xargs -r docker stop | xargs -r docker rm && npm run dev -- --host 0.0.0.0"]
